version: '3.8'

services:
  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
      - ./input:/usr/src/app/input
    ports:
      - 5001:5001
    env_file:
      - ./.env.dev

volumes:
  input:
